# Site settings
title: Good Iterations
email: steve.coppin@gmail.com
description: Life's too short not be excited about what you do. Case studies and strategies to get you and your digital team firing on all cyclinders.
baseurl: ""
url: "http://gooditerations.com"
keywords: "good, iterations, digital, delivery, coppin-smith, leadership"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
