# Site settings
title: Good Iterations
email: steve.coppin@gmail.com
description: Life's too short not be excited about what you do. Digital should be engaging, rewarding and fun. A collection of case studies and strategies to get your digital team firing on all cyclinders.
baseurl: ""
url: "http://gooditerations.com"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
