# Site settings
title: Good Iterations
email: steve@gooditerations.com
description: Reclaim your team bliss and let's start enjoying software delivery again. 
baseurl: ""
url: "https://gooditerations.com"
keywords: "good, iterations, good iterations, digital, delivery, coppin-smith, leadership, autonomy, performance, teams, scaling, consultant, consultancy"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
