# Site settings
title: Good Iterations
email: steve@gooditerations.com
description: Life's too short not be excited about what you do. Good Iterations are determined to help you get there.
baseurl: ""
url: "http://gooditerations.com"
keywords: "good, iterations, good iterations, digital, delivery, coppin-smith, leadership, autonomy, performance, teams, scaling"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
